[package]
name = "leptos_ws"
version = "0.1.0"
edition = "2021"

[dependencies]
json-patch = "2.0.0"
leptos = { version = "=0.7.0-beta2", default-features = false }

serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = { version = "1" }
async-trait = "0.1"

# Axum
axum = { version = "0.7", default-features = false, features = [
    "ws",
], optional = true }
futures = { version = "0.3", default-features = false, optional = true }

wasm-bindgen = { version = "0.2", default-features = false }
web-sys = { version = "0.3", features = ["WebSocket", "MessageEvent"] }
send_wrapper = "0.6.0"
tokio = { version = "1.38.0", optional = true, features = ["rt-multi-thread"] }

[features]
default = []
ssr = ["leptos/ssr", "dep:tokio", "dep:futures"]
axum = ["dep:axum"]
